// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.language.authoring.models;

import com.azure.core.annotation.Fluent;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;

/** Represents a warning that was encountered while executing the request. */
@Fluent
public final class JobWarning {
    /*
     * The warning code.
     */
    @JsonProperty(value = "code", required = true)
    private String code;

    /*
     * The warning message.
     */
    @JsonProperty(value = "message", required = true)
    private String message;

    /**
     * Creates an instance of JobWarning class.
     *
     * @param code the code value to set.
     * @param message the message value to set.
     */
    @JsonCreator
    public JobWarning(
            @JsonProperty(value = "code", required = true) String code,
            @JsonProperty(value = "message", required = true) String message) {
        this.code = code;
        this.message = message;
    }

    /**
     * Get the code property: The warning code.
     *
     * @return the code value.
     */
    public String getCode() {
        return this.code;
    }

    /**
     * Get the message property: The warning message.
     *
     * @return the message value.
     */
    public String getMessage() {
        return this.message;
    }
}
