// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.language.authoring.models;

import com.azure.core.annotation.Fluent;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;

/** The SwapDeploymentsOptions model. */
@Fluent
public final class SwapDeploymentsOptions {
    /*
     * Represents the first deployment name.
     */
    @JsonProperty(value = "firstDeploymentName", required = true)
    private String firstDeploymentName;

    /*
     * Represents the second deployment name.
     */
    @JsonProperty(value = "secondDeploymentName", required = true)
    private String secondDeploymentName;

    /**
     * Creates an instance of SwapDeploymentsOptions class.
     *
     * @param firstDeploymentName the firstDeploymentName value to set.
     * @param secondDeploymentName the secondDeploymentName value to set.
     */
    @JsonCreator
    public SwapDeploymentsOptions(
            @JsonProperty(value = "firstDeploymentName", required = true) String firstDeploymentName,
            @JsonProperty(value = "secondDeploymentName", required = true) String secondDeploymentName) {
        this.firstDeploymentName = firstDeploymentName;
        this.secondDeploymentName = secondDeploymentName;
    }

    /**
     * Get the firstDeploymentName property: Represents the first deployment name.
     *
     * @return the firstDeploymentName value.
     */
    public String getFirstDeploymentName() {
        return this.firstDeploymentName;
    }

    /**
     * Get the secondDeploymentName property: Represents the second deployment name.
     *
     * @return the secondDeploymentName value.
     */
    public String getSecondDeploymentName() {
        return this.secondDeploymentName;
    }
}
