// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.ai.language.textanalytics.models;

import com.azure.core.annotation.Fluent;
import com.fasterxml.jackson.annotation.JsonProperty;

/** Parameters object for a text analysis task using pre-built models. */
@Fluent
public final class KeyPhraseTaskParameters {
    /*
     * If set to true, you opt-out of having your text input logged for troubleshooting.
     */
    @JsonProperty(value = "loggingOptOut")
    private Boolean loggingOptOut;

    /*
     * This field indicates which model is used for scoring.
     */
    @JsonProperty(value = "modelVersion")
    private String modelVersion;

    /**
     * Get the loggingOptOut property: If set to true, you opt-out of having your text input logged for troubleshooting.
     *
     * @return the loggingOptOut value.
     */
    public Boolean isLoggingOptOut() {
        return this.loggingOptOut;
    }

    /**
     * Set the loggingOptOut property: If set to true, you opt-out of having your text input logged for troubleshooting.
     *
     * @param loggingOptOut the loggingOptOut value to set.
     * @return the KeyPhraseTaskParameters object itself.
     */
    public KeyPhraseTaskParameters setLoggingOptOut(Boolean loggingOptOut) {
        this.loggingOptOut = loggingOptOut;
        return this;
    }

    /**
     * Get the modelVersion property: This field indicates which model is used for scoring.
     *
     * @return the modelVersion value.
     */
    public String getModelVersion() {
        return this.modelVersion;
    }

    /**
     * Set the modelVersion property: This field indicates which model is used for scoring.
     *
     * @param modelVersion the modelVersion value to set.
     * @return the KeyPhraseTaskParameters object itself.
     */
    public KeyPhraseTaskParameters setModelVersion(String modelVersion) {
        this.modelVersion = modelVersion;
        return this;
    }
}
