// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.ai.language.textanalytics.models;

import com.azure.core.annotation.Immutable;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;

/** The LanguageDetectionAnalysisInput model. */
@Immutable
public final class LanguageDetectionAnalysisInput {
    /*
     * Collection of documents to analyze.
     */
    @JsonProperty(value = "documents", required = true)
    private List<LanguageInput> documents;

    /**
     * Creates an instance of LanguageDetectionAnalysisInput class.
     *
     * @param documents the documents value to set.
     */
    @JsonCreator
    public LanguageDetectionAnalysisInput(
            @JsonProperty(value = "documents", required = true) List<LanguageInput> documents) {
        this.documents = documents;
    }

    /**
     * Get the documents property: Collection of documents to analyze.
     *
     * @return the documents value.
     */
    public List<LanguageInput> getDocuments() {
        return this.documents;
    }
}
