// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.ai.language.textanalytics.models;

import com.azure.core.util.ExpandableStringEnum;
import com.fasterxml.jackson.annotation.JsonCreator;
import java.util.Collection;

/** Defines values for PiiCategories. */
public final class PiiCategories extends ExpandableStringEnum<PiiCategories> {
    /** Static value ABARoutingNumber for PiiCategories. */
    public static final PiiCategories ABAROUTING_NUMBER = fromString("ABARoutingNumber");

    /** Static value ARNationalIdentityNumber for PiiCategories. */
    public static final PiiCategories ARNATIONAL_IDENTITY_NUMBER = fromString("ARNationalIdentityNumber");

    /** Static value AUBankAccountNumber for PiiCategories. */
    public static final PiiCategories AUBANK_ACCOUNT_NUMBER = fromString("AUBankAccountNumber");

    /** Static value AUDriversLicenseNumber for PiiCategories. */
    public static final PiiCategories AUDRIVERS_LICENSE_NUMBER = fromString("AUDriversLicenseNumber");

    /** Static value AUMedicalAccountNumber for PiiCategories. */
    public static final PiiCategories AUMEDICAL_ACCOUNT_NUMBER = fromString("AUMedicalAccountNumber");

    /** Static value AUPassportNumber for PiiCategories. */
    public static final PiiCategories AUPASSPORT_NUMBER = fromString("AUPassportNumber");

    /** Static value AUTaxFileNumber for PiiCategories. */
    public static final PiiCategories AUTAX_FILE_NUMBER = fromString("AUTaxFileNumber");

    /** Static value AUBusinessNumber for PiiCategories. */
    public static final PiiCategories AUBUSINESS_NUMBER = fromString("AUBusinessNumber");

    /** Static value AUCompanyNumber for PiiCategories. */
    public static final PiiCategories AUCOMPANY_NUMBER = fromString("AUCompanyNumber");

    /** Static value ATIdentityCard for PiiCategories. */
    public static final PiiCategories ATIDENTITY_CARD = fromString("ATIdentityCard");

    /** Static value ATTaxIdentificationNumber for PiiCategories. */
    public static final PiiCategories ATTAX_IDENTIFICATION_NUMBER = fromString("ATTaxIdentificationNumber");

    /** Static value ATValueAddedTaxNumber for PiiCategories. */
    public static final PiiCategories ATVALUE_ADDED_TAX_NUMBER = fromString("ATValueAddedTaxNumber");

    /** Static value AzureDocumentDBAuthKey for PiiCategories. */
    public static final PiiCategories AZURE_DOCUMENT_DBAUTH_KEY = fromString("AzureDocumentDBAuthKey");

    /** Static value AzureIAASDatabaseConnectionAndSQLString for PiiCategories. */
    public static final PiiCategories AZURE_IAASDATABASE_CONNECTION_AND_SQLSTRING =
            fromString("AzureIAASDatabaseConnectionAndSQLString");

    /** Static value AzureIoTConnectionString for PiiCategories. */
    public static final PiiCategories AZURE_IO_TCONNECTION_STRING = fromString("AzureIoTConnectionString");

    /** Static value AzurePublishSettingPassword for PiiCategories. */
    public static final PiiCategories AZURE_PUBLISH_SETTING_PASSWORD = fromString("AzurePublishSettingPassword");

    /** Static value AzureRedisCacheString for PiiCategories. */
    public static final PiiCategories AZURE_REDIS_CACHE_STRING = fromString("AzureRedisCacheString");

    /** Static value AzureSAS for PiiCategories. */
    public static final PiiCategories AZURE_SAS = fromString("AzureSAS");

    /** Static value AzureServiceBusString for PiiCategories. */
    public static final PiiCategories AZURE_SERVICE_BUS_STRING = fromString("AzureServiceBusString");

    /** Static value AzureStorageAccountKey for PiiCategories. */
    public static final PiiCategories AZURE_STORAGE_ACCOUNT_KEY = fromString("AzureStorageAccountKey");

    /** Static value AzureStorageAccountGeneric for PiiCategories. */
    public static final PiiCategories AZURE_STORAGE_ACCOUNT_GENERIC = fromString("AzureStorageAccountGeneric");

    /** Static value BENationalNumber for PiiCategories. */
    public static final PiiCategories BENATIONAL_NUMBER = fromString("BENationalNumber");

    /** Static value BENationalNumberV2 for PiiCategories. */
    public static final PiiCategories BENATIONAL_NUMBER_V2 = fromString("BENationalNumberV2");

    /** Static value BEValueAddedTaxNumber for PiiCategories. */
    public static final PiiCategories BEVALUE_ADDED_TAX_NUMBER = fromString("BEValueAddedTaxNumber");

    /** Static value BRCPFNumber for PiiCategories. */
    public static final PiiCategories BRCPFNUMBER = fromString("BRCPFNumber");

    /** Static value BRLegalEntityNumber for PiiCategories. */
    public static final PiiCategories BRLEGAL_ENTITY_NUMBER = fromString("BRLegalEntityNumber");

    /** Static value BRNationalIDRG for PiiCategories. */
    public static final PiiCategories BRNATIONAL_IDRG = fromString("BRNationalIDRG");

    /** Static value BGUniformCivilNumber for PiiCategories. */
    public static final PiiCategories BGUNIFORM_CIVIL_NUMBER = fromString("BGUniformCivilNumber");

    /** Static value CABankAccountNumber for PiiCategories. */
    public static final PiiCategories CABANK_ACCOUNT_NUMBER = fromString("CABankAccountNumber");

    /** Static value CADriversLicenseNumber for PiiCategories. */
    public static final PiiCategories CADRIVERS_LICENSE_NUMBER = fromString("CADriversLicenseNumber");

    /** Static value CAHealthServiceNumber for PiiCategories. */
    public static final PiiCategories CAHEALTH_SERVICE_NUMBER = fromString("CAHealthServiceNumber");

    /** Static value CAPassportNumber for PiiCategories. */
    public static final PiiCategories CAPASSPORT_NUMBER = fromString("CAPassportNumber");

    /** Static value CAPersonalHealthIdentification for PiiCategories. */
    public static final PiiCategories CAPERSONAL_HEALTH_IDENTIFICATION = fromString("CAPersonalHealthIdentification");

    /** Static value CASocialInsuranceNumber for PiiCategories. */
    public static final PiiCategories CASOCIAL_INSURANCE_NUMBER = fromString("CASocialInsuranceNumber");

    /** Static value CLIdentityCardNumber for PiiCategories. */
    public static final PiiCategories CLIDENTITY_CARD_NUMBER = fromString("CLIdentityCardNumber");

    /** Static value CNResidentIdentityCardNumber for PiiCategories. */
    public static final PiiCategories CNRESIDENT_IDENTITY_CARD_NUMBER = fromString("CNResidentIdentityCardNumber");

    /** Static value CreditCardNumber for PiiCategories. */
    public static final PiiCategories CREDIT_CARD_NUMBER = fromString("CreditCardNumber");

    /** Static value HRIdentityCardNumber for PiiCategories. */
    public static final PiiCategories HRIDENTITY_CARD_NUMBER = fromString("HRIdentityCardNumber");

    /** Static value HRNationalIDNumber for PiiCategories. */
    public static final PiiCategories HRNATIONAL_IDNUMBER = fromString("HRNationalIDNumber");

    /** Static value HRPersonalIdentificationNumber for PiiCategories. */
    public static final PiiCategories HRPERSONAL_IDENTIFICATION_NUMBER = fromString("HRPersonalIdentificationNumber");

    /** Static value HRPersonalIdentificationOIBNumberV2 for PiiCategories. */
    public static final PiiCategories HRPERSONAL_IDENTIFICATION_OIBNUMBER_V2 =
            fromString("HRPersonalIdentificationOIBNumberV2");

    /** Static value CYIdentityCard for PiiCategories. */
    public static final PiiCategories CYIDENTITY_CARD = fromString("CYIdentityCard");

    /** Static value CYTaxIdentificationNumber for PiiCategories. */
    public static final PiiCategories CYTAX_IDENTIFICATION_NUMBER = fromString("CYTaxIdentificationNumber");

    /** Static value CZPersonalIdentityNumber for PiiCategories. */
    public static final PiiCategories CZPERSONAL_IDENTITY_NUMBER = fromString("CZPersonalIdentityNumber");

    /** Static value CZPersonalIdentityV2 for PiiCategories. */
    public static final PiiCategories CZPERSONAL_IDENTITY_V2 = fromString("CZPersonalIdentityV2");

    /** Static value DKPersonalIdentificationNumber for PiiCategories. */
    public static final PiiCategories DKPERSONAL_IDENTIFICATION_NUMBER = fromString("DKPersonalIdentificationNumber");

    /** Static value DKPersonalIdentificationV2 for PiiCategories. */
    public static final PiiCategories DKPERSONAL_IDENTIFICATION_V2 = fromString("DKPersonalIdentificationV2");

    /** Static value DrugEnforcementAgencyNumber for PiiCategories. */
    public static final PiiCategories DRUG_ENFORCEMENT_AGENCY_NUMBER = fromString("DrugEnforcementAgencyNumber");

    /** Static value EEPersonalIdentificationCode for PiiCategories. */
    public static final PiiCategories EEPERSONAL_IDENTIFICATION_CODE = fromString("EEPersonalIdentificationCode");

    /** Static value EUDebitCardNumber for PiiCategories. */
    public static final PiiCategories EUDEBIT_CARD_NUMBER = fromString("EUDebitCardNumber");

    /** Static value EUDriversLicenseNumber for PiiCategories. */
    public static final PiiCategories EUDRIVERS_LICENSE_NUMBER = fromString("EUDriversLicenseNumber");

    /** Static value EUGPSCoordinates for PiiCategories. */
    public static final PiiCategories EUGPSCOORDINATES = fromString("EUGPSCoordinates");

    /** Static value EUNationalIdentificationNumber for PiiCategories. */
    public static final PiiCategories EUNATIONAL_IDENTIFICATION_NUMBER = fromString("EUNationalIdentificationNumber");

    /** Static value EUPassportNumber for PiiCategories. */
    public static final PiiCategories EUPASSPORT_NUMBER = fromString("EUPassportNumber");

    /** Static value EUSocialSecurityNumber for PiiCategories. */
    public static final PiiCategories EUSOCIAL_SECURITY_NUMBER = fromString("EUSocialSecurityNumber");

    /** Static value EUTaxIdentificationNumber for PiiCategories. */
    public static final PiiCategories EUTAX_IDENTIFICATION_NUMBER = fromString("EUTaxIdentificationNumber");

    /** Static value FIEuropeanHealthNumber for PiiCategories. */
    public static final PiiCategories FIEUROPEAN_HEALTH_NUMBER = fromString("FIEuropeanHealthNumber");

    /** Static value FINationalID for PiiCategories. */
    public static final PiiCategories FINATIONAL_ID = fromString("FINationalID");

    /** Static value FINationalIDV2 for PiiCategories. */
    public static final PiiCategories FINATIONAL_IDV2 = fromString("FINationalIDV2");

    /** Static value FIPassportNumber for PiiCategories. */
    public static final PiiCategories FIPASSPORT_NUMBER = fromString("FIPassportNumber");

    /** Static value FRDriversLicenseNumber for PiiCategories. */
    public static final PiiCategories FRDRIVERS_LICENSE_NUMBER = fromString("FRDriversLicenseNumber");

    /** Static value FRHealthInsuranceNumber for PiiCategories. */
    public static final PiiCategories FRHEALTH_INSURANCE_NUMBER = fromString("FRHealthInsuranceNumber");

    /** Static value FRNationalID for PiiCategories. */
    public static final PiiCategories FRNATIONAL_ID = fromString("FRNationalID");

    /** Static value FRPassportNumber for PiiCategories. */
    public static final PiiCategories FRPASSPORT_NUMBER = fromString("FRPassportNumber");

    /** Static value FRSocialSecurityNumber for PiiCategories. */
    public static final PiiCategories FRSOCIAL_SECURITY_NUMBER = fromString("FRSocialSecurityNumber");

    /** Static value FRTaxIdentificationNumber for PiiCategories. */
    public static final PiiCategories FRTAX_IDENTIFICATION_NUMBER = fromString("FRTaxIdentificationNumber");

    /** Static value FRValueAddedTaxNumber for PiiCategories. */
    public static final PiiCategories FRVALUE_ADDED_TAX_NUMBER = fromString("FRValueAddedTaxNumber");

    /** Static value DEDriversLicenseNumber for PiiCategories. */
    public static final PiiCategories DEDRIVERS_LICENSE_NUMBER = fromString("DEDriversLicenseNumber");

    /** Static value DEPassportNumber for PiiCategories. */
    public static final PiiCategories DEPASSPORT_NUMBER = fromString("DEPassportNumber");

    /** Static value DEIdentityCardNumber for PiiCategories. */
    public static final PiiCategories DEIDENTITY_CARD_NUMBER = fromString("DEIdentityCardNumber");

    /** Static value DETaxIdentificationNumber for PiiCategories. */
    public static final PiiCategories DETAX_IDENTIFICATION_NUMBER = fromString("DETaxIdentificationNumber");

    /** Static value DEValueAddedNumber for PiiCategories. */
    public static final PiiCategories DEVALUE_ADDED_NUMBER = fromString("DEValueAddedNumber");

    /** Static value GRNationalIDCard for PiiCategories. */
    public static final PiiCategories GRNATIONAL_IDCARD = fromString("GRNationalIDCard");

    /** Static value GRNationalIDV2 for PiiCategories. */
    public static final PiiCategories GRNATIONAL_IDV2 = fromString("GRNationalIDV2");

    /** Static value GRTaxIdentificationNumber for PiiCategories. */
    public static final PiiCategories GRTAX_IDENTIFICATION_NUMBER = fromString("GRTaxIdentificationNumber");

    /** Static value HKIdentityCardNumber for PiiCategories. */
    public static final PiiCategories HKIDENTITY_CARD_NUMBER = fromString("HKIdentityCardNumber");

    /** Static value HUValueAddedNumber for PiiCategories. */
    public static final PiiCategories HUVALUE_ADDED_NUMBER = fromString("HUValueAddedNumber");

    /** Static value HUPersonalIdentificationNumber for PiiCategories. */
    public static final PiiCategories HUPERSONAL_IDENTIFICATION_NUMBER = fromString("HUPersonalIdentificationNumber");

    /** Static value HUTaxIdentificationNumber for PiiCategories. */
    public static final PiiCategories HUTAX_IDENTIFICATION_NUMBER = fromString("HUTaxIdentificationNumber");

    /** Static value INPermanentAccount for PiiCategories. */
    public static final PiiCategories INPERMANENT_ACCOUNT = fromString("INPermanentAccount");

    /** Static value INUniqueIdentificationNumber for PiiCategories. */
    public static final PiiCategories INUNIQUE_IDENTIFICATION_NUMBER = fromString("INUniqueIdentificationNumber");

    /** Static value IDIdentityCardNumber for PiiCategories. */
    public static final PiiCategories IDIDENTITY_CARD_NUMBER = fromString("IDIdentityCardNumber");

    /** Static value InternationalBankingAccountNumber for PiiCategories. */
    public static final PiiCategories INTERNATIONAL_BANKING_ACCOUNT_NUMBER =
            fromString("InternationalBankingAccountNumber");

    /** Static value IEPersonalPublicServiceNumber for PiiCategories. */
    public static final PiiCategories IEPERSONAL_PUBLIC_SERVICE_NUMBER = fromString("IEPersonalPublicServiceNumber");

    /** Static value IEPersonalPublicServiceNumberV2 for PiiCategories. */
    public static final PiiCategories IEPERSONAL_PUBLIC_SERVICE_NUMBER_V2 =
            fromString("IEPersonalPublicServiceNumberV2");

    /** Static value ILBankAccountNumber for PiiCategories. */
    public static final PiiCategories ILBANK_ACCOUNT_NUMBER = fromString("ILBankAccountNumber");

    /** Static value ILNationalID for PiiCategories. */
    public static final PiiCategories ILNATIONAL_ID = fromString("ILNationalID");

    /** Static value ITDriversLicenseNumber for PiiCategories. */
    public static final PiiCategories ITDRIVERS_LICENSE_NUMBER = fromString("ITDriversLicenseNumber");

    /** Static value ITFiscalCode for PiiCategories. */
    public static final PiiCategories ITFISCAL_CODE = fromString("ITFiscalCode");

    /** Static value ITValueAddedTaxNumber for PiiCategories. */
    public static final PiiCategories ITVALUE_ADDED_TAX_NUMBER = fromString("ITValueAddedTaxNumber");

    /** Static value JPBankAccountNumber for PiiCategories. */
    public static final PiiCategories JPBANK_ACCOUNT_NUMBER = fromString("JPBankAccountNumber");

    /** Static value JPDriversLicenseNumber for PiiCategories. */
    public static final PiiCategories JPDRIVERS_LICENSE_NUMBER = fromString("JPDriversLicenseNumber");

    /** Static value JPPassportNumber for PiiCategories. */
    public static final PiiCategories JPPASSPORT_NUMBER = fromString("JPPassportNumber");

    /** Static value JPResidentRegistrationNumber for PiiCategories. */
    public static final PiiCategories JPRESIDENT_REGISTRATION_NUMBER = fromString("JPResidentRegistrationNumber");

    /** Static value JPSocialInsuranceNumber for PiiCategories. */
    public static final PiiCategories JPSOCIAL_INSURANCE_NUMBER = fromString("JPSocialInsuranceNumber");

    /** Static value JPMyNumberCorporate for PiiCategories. */
    public static final PiiCategories JPMY_NUMBER_CORPORATE = fromString("JPMyNumberCorporate");

    /** Static value JPMyNumberPersonal for PiiCategories. */
    public static final PiiCategories JPMY_NUMBER_PERSONAL = fromString("JPMyNumberPersonal");

    /** Static value JPResidenceCardNumber for PiiCategories. */
    public static final PiiCategories JPRESIDENCE_CARD_NUMBER = fromString("JPResidenceCardNumber");

    /** Static value LVPersonalCode for PiiCategories. */
    public static final PiiCategories LVPERSONAL_CODE = fromString("LVPersonalCode");

    /** Static value LTPersonalCode for PiiCategories. */
    public static final PiiCategories LTPERSONAL_CODE = fromString("LTPersonalCode");

    /** Static value LUNationalIdentificationNumberNatural for PiiCategories. */
    public static final PiiCategories LUNATIONAL_IDENTIFICATION_NUMBER_NATURAL =
            fromString("LUNationalIdentificationNumberNatural");

    /** Static value LUNationalIdentificationNumberNonNatural for PiiCategories. */
    public static final PiiCategories LUNATIONAL_IDENTIFICATION_NUMBER_NON_NATURAL =
            fromString("LUNationalIdentificationNumberNonNatural");

    /** Static value MYIdentityCardNumber for PiiCategories. */
    public static final PiiCategories MYIDENTITY_CARD_NUMBER = fromString("MYIdentityCardNumber");

    /** Static value MTIdentityCardNumber for PiiCategories. */
    public static final PiiCategories MTIDENTITY_CARD_NUMBER = fromString("MTIdentityCardNumber");

    /** Static value MTTaxIDNumber for PiiCategories. */
    public static final PiiCategories MTTAX_IDNUMBER = fromString("MTTaxIDNumber");

    /** Static value NLCitizensServiceNumber for PiiCategories. */
    public static final PiiCategories NLCITIZENS_SERVICE_NUMBER = fromString("NLCitizensServiceNumber");

    /** Static value NLCitizensServiceNumberV2 for PiiCategories. */
    public static final PiiCategories NLCITIZENS_SERVICE_NUMBER_V2 = fromString("NLCitizensServiceNumberV2");

    /** Static value NLTaxIdentificationNumber for PiiCategories. */
    public static final PiiCategories NLTAX_IDENTIFICATION_NUMBER = fromString("NLTaxIdentificationNumber");

    /** Static value NLValueAddedTaxNumber for PiiCategories. */
    public static final PiiCategories NLVALUE_ADDED_TAX_NUMBER = fromString("NLValueAddedTaxNumber");

    /** Static value NZBankAccountNumber for PiiCategories. */
    public static final PiiCategories NZBANK_ACCOUNT_NUMBER = fromString("NZBankAccountNumber");

    /** Static value NZDriversLicenseNumber for PiiCategories. */
    public static final PiiCategories NZDRIVERS_LICENSE_NUMBER = fromString("NZDriversLicenseNumber");

    /** Static value NZInlandRevenueNumber for PiiCategories. */
    public static final PiiCategories NZINLAND_REVENUE_NUMBER = fromString("NZInlandRevenueNumber");

    /** Static value NZMinistryOfHealthNumber for PiiCategories. */
    public static final PiiCategories NZMINISTRY_OF_HEALTH_NUMBER = fromString("NZMinistryOfHealthNumber");

    /** Static value NZSocialWelfareNumber for PiiCategories. */
    public static final PiiCategories NZSOCIAL_WELFARE_NUMBER = fromString("NZSocialWelfareNumber");

    /** Static value NOIdentityNumber for PiiCategories. */
    public static final PiiCategories NOIDENTITY_NUMBER = fromString("NOIdentityNumber");

    /** Static value PHUnifiedMultiPurposeIDNumber for PiiCategories. */
    public static final PiiCategories PHUNIFIED_MULTI_PURPOSE_IDNUMBER = fromString("PHUnifiedMultiPurposeIDNumber");

    /** Static value PLIdentityCard for PiiCategories. */
    public static final PiiCategories PLIDENTITY_CARD = fromString("PLIdentityCard");

    /** Static value PLNationalID for PiiCategories. */
    public static final PiiCategories PLNATIONAL_ID = fromString("PLNationalID");

    /** Static value PLNationalIDV2 for PiiCategories. */
    public static final PiiCategories PLNATIONAL_IDV2 = fromString("PLNationalIDV2");

    /** Static value PLPassportNumber for PiiCategories. */
    public static final PiiCategories PLPASSPORT_NUMBER = fromString("PLPassportNumber");

    /** Static value PLTaxIdentificationNumber for PiiCategories. */
    public static final PiiCategories PLTAX_IDENTIFICATION_NUMBER = fromString("PLTaxIdentificationNumber");

    /** Static value PLREGONNumber for PiiCategories. */
    public static final PiiCategories PLREGONNUMBER = fromString("PLREGONNumber");

    /** Static value PTCitizenCardNumber for PiiCategories. */
    public static final PiiCategories PTCITIZEN_CARD_NUMBER = fromString("PTCitizenCardNumber");

    /** Static value PTCitizenCardNumberV2 for PiiCategories. */
    public static final PiiCategories PTCITIZEN_CARD_NUMBER_V2 = fromString("PTCitizenCardNumberV2");

    /** Static value PTTaxIdentificationNumber for PiiCategories. */
    public static final PiiCategories PTTAX_IDENTIFICATION_NUMBER = fromString("PTTaxIdentificationNumber");

    /** Static value ROPersonalNumericalCode for PiiCategories. */
    public static final PiiCategories ROPERSONAL_NUMERICAL_CODE = fromString("ROPersonalNumericalCode");

    /** Static value RUPassportNumberDomestic for PiiCategories. */
    public static final PiiCategories RUPASSPORT_NUMBER_DOMESTIC = fromString("RUPassportNumberDomestic");

    /** Static value RUPassportNumberInternational for PiiCategories. */
    public static final PiiCategories RUPASSPORT_NUMBER_INTERNATIONAL = fromString("RUPassportNumberInternational");

    /** Static value SANationalID for PiiCategories. */
    public static final PiiCategories SANATIONAL_ID = fromString("SANationalID");

    /** Static value SGNationalRegistrationIdentityCardNumber for PiiCategories. */
    public static final PiiCategories SGNATIONAL_REGISTRATION_IDENTITY_CARD_NUMBER =
            fromString("SGNationalRegistrationIdentityCardNumber");

    /** Static value SKPersonalNumber for PiiCategories. */
    public static final PiiCategories SKPERSONAL_NUMBER = fromString("SKPersonalNumber");

    /** Static value SITaxIdentificationNumber for PiiCategories. */
    public static final PiiCategories SITAX_IDENTIFICATION_NUMBER = fromString("SITaxIdentificationNumber");

    /** Static value SIUniqueMasterCitizenNumber for PiiCategories. */
    public static final PiiCategories SIUNIQUE_MASTER_CITIZEN_NUMBER = fromString("SIUniqueMasterCitizenNumber");

    /** Static value ZAIdentificationNumber for PiiCategories. */
    public static final PiiCategories ZAIDENTIFICATION_NUMBER = fromString("ZAIdentificationNumber");

    /** Static value KRResidentRegistrationNumber for PiiCategories. */
    public static final PiiCategories KRRESIDENT_REGISTRATION_NUMBER = fromString("KRResidentRegistrationNumber");

    /** Static value ESDNI for PiiCategories. */
    public static final PiiCategories ESDNI = fromString("ESDNI");

    /** Static value ESSocialSecurityNumber for PiiCategories. */
    public static final PiiCategories ESSOCIAL_SECURITY_NUMBER = fromString("ESSocialSecurityNumber");

    /** Static value ESTaxIdentificationNumber for PiiCategories. */
    public static final PiiCategories ESTAX_IDENTIFICATION_NUMBER = fromString("ESTaxIdentificationNumber");

    /** Static value SQLServerConnectionString for PiiCategories. */
    public static final PiiCategories SQLSERVER_CONNECTION_STRING = fromString("SQLServerConnectionString");

    /** Static value SENationalID for PiiCategories. */
    public static final PiiCategories SENATIONAL_ID = fromString("SENationalID");

    /** Static value SENationalIDV2 for PiiCategories. */
    public static final PiiCategories SENATIONAL_IDV2 = fromString("SENationalIDV2");

    /** Static value SEPassportNumber for PiiCategories. */
    public static final PiiCategories SEPASSPORT_NUMBER = fromString("SEPassportNumber");

    /** Static value SETaxIdentificationNumber for PiiCategories. */
    public static final PiiCategories SETAX_IDENTIFICATION_NUMBER = fromString("SETaxIdentificationNumber");

    /** Static value SWIFTCode for PiiCategories. */
    public static final PiiCategories SWIFTCODE = fromString("SWIFTCode");

    /** Static value CHSocialSecurityNumber for PiiCategories. */
    public static final PiiCategories CHSOCIAL_SECURITY_NUMBER = fromString("CHSocialSecurityNumber");

    /** Static value TWNationalID for PiiCategories. */
    public static final PiiCategories TWNATIONAL_ID = fromString("TWNationalID");

    /** Static value TWPassportNumber for PiiCategories. */
    public static final PiiCategories TWPASSPORT_NUMBER = fromString("TWPassportNumber");

    /** Static value TWResidentCertificate for PiiCategories. */
    public static final PiiCategories TWRESIDENT_CERTIFICATE = fromString("TWResidentCertificate");

    /** Static value THPopulationIdentificationCode for PiiCategories. */
    public static final PiiCategories THPOPULATION_IDENTIFICATION_CODE = fromString("THPopulationIdentificationCode");

    /** Static value TRNationalIdentificationNumber for PiiCategories. */
    public static final PiiCategories TRNATIONAL_IDENTIFICATION_NUMBER = fromString("TRNationalIdentificationNumber");

    /** Static value UKDriversLicenseNumber for PiiCategories. */
    public static final PiiCategories UKDRIVERS_LICENSE_NUMBER = fromString("UKDriversLicenseNumber");

    /** Static value UKElectoralRollNumber for PiiCategories. */
    public static final PiiCategories UKELECTORAL_ROLL_NUMBER = fromString("UKElectoralRollNumber");

    /** Static value UKNationalHealthNumber for PiiCategories. */
    public static final PiiCategories UKNATIONAL_HEALTH_NUMBER = fromString("UKNationalHealthNumber");

    /** Static value UKNationalInsuranceNumber for PiiCategories. */
    public static final PiiCategories UKNATIONAL_INSURANCE_NUMBER = fromString("UKNationalInsuranceNumber");

    /** Static value UKUniqueTaxpayerNumber for PiiCategories. */
    public static final PiiCategories UKUNIQUE_TAXPAYER_NUMBER = fromString("UKUniqueTaxpayerNumber");

    /** Static value USUKPassportNumber for PiiCategories. */
    public static final PiiCategories USUKPASSPORT_NUMBER = fromString("USUKPassportNumber");

    /** Static value USBankAccountNumber for PiiCategories. */
    public static final PiiCategories USBANK_ACCOUNT_NUMBER = fromString("USBankAccountNumber");

    /** Static value USDriversLicenseNumber for PiiCategories. */
    public static final PiiCategories USDRIVERS_LICENSE_NUMBER = fromString("USDriversLicenseNumber");

    /** Static value USIndividualTaxpayerIdentification for PiiCategories. */
    public static final PiiCategories USINDIVIDUAL_TAXPAYER_IDENTIFICATION =
            fromString("USIndividualTaxpayerIdentification");

    /** Static value USSocialSecurityNumber for PiiCategories. */
    public static final PiiCategories USSOCIAL_SECURITY_NUMBER = fromString("USSocialSecurityNumber");

    /** Static value UAPassportNumberDomestic for PiiCategories. */
    public static final PiiCategories UAPASSPORT_NUMBER_DOMESTIC = fromString("UAPassportNumberDomestic");

    /** Static value UAPassportNumberInternational for PiiCategories. */
    public static final PiiCategories UAPASSPORT_NUMBER_INTERNATIONAL = fromString("UAPassportNumberInternational");

    /** Static value Organization for PiiCategories. */
    public static final PiiCategories ORGANIZATION = fromString("Organization");

    /** Static value Email for PiiCategories. */
    public static final PiiCategories EMAIL = fromString("Email");

    /** Static value URL for PiiCategories. */
    public static final PiiCategories URL = fromString("URL");

    /** Static value Age for PiiCategories. */
    public static final PiiCategories AGE = fromString("Age");

    /** Static value PhoneNumber for PiiCategories. */
    public static final PiiCategories PHONE_NUMBER = fromString("PhoneNumber");

    /** Static value IPAddress for PiiCategories. */
    public static final PiiCategories IPADDRESS = fromString("IPAddress");

    /** Static value Date for PiiCategories. */
    public static final PiiCategories DATE = fromString("Date");

    /** Static value Person for PiiCategories. */
    public static final PiiCategories PERSON = fromString("Person");

    /** Static value Address for PiiCategories. */
    public static final PiiCategories ADDRESS = fromString("Address");

    /** Static value All for PiiCategories. */
    public static final PiiCategories ALL = fromString("All");

    /** Static value Default for PiiCategories. */
    public static final PiiCategories DEFAULT = fromString("Default");

    /**
     * Creates or finds a PiiCategories from its string representation.
     *
     * @param name a name to look for.
     * @return the corresponding PiiCategories.
     */
    @JsonCreator
    public static PiiCategories fromString(String name) {
        return fromString(name, PiiCategories.class);
    }

    /**
     * Gets known PiiCategories values.
     *
     * @return known PiiCategories values.
     */
    public static Collection<PiiCategories> values() {
        return values(PiiCategories.class);
    }
}
