// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.ai.language.textanalytics.models;

import com.azure.core.annotation.Immutable;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;

/** The SentimentDocumentResult model. */
@Immutable
public final class SentimentDocumentResult {
    /*
     * Unique, non-empty document identifier.
     */
    @JsonProperty(value = "id", required = true)
    private String id;

    /*
     * Warnings encountered while processing document.
     */
    @JsonProperty(value = "warnings", required = true)
    private List<DocumentWarning> warnings;

    /*
     * If showStats=true was specified in the request this field will contain information about the document payload.
     */
    @JsonProperty(value = "statistics", required = true)
    private List<DocumentStatistics> statistics;

    /*
     * Predicted sentiment for document.
     */
    @JsonProperty(value = "sentiment", required = true)
    private DocumentSentimentValue sentiment;

    /*
     * Sentence level sentiment analysis.
     */
    @JsonProperty(value = "sentences", required = true)
    private List<SentenceSentiment> sentences;

    /*
     * Document level sentiment confidence scores between 0 and 1 for each sentiment class.
     */
    @JsonProperty(value = "confidenceScores", required = true)
    private SentimentConfidenceScorePerLabel confidenceScores;

    /**
     * Creates an instance of SentimentDocumentResult class.
     *
     * @param id the id value to set.
     * @param warnings the warnings value to set.
     * @param statistics the statistics value to set.
     * @param sentiment the sentiment value to set.
     * @param sentences the sentences value to set.
     * @param confidenceScores the confidenceScores value to set.
     */
    @JsonCreator
    public SentimentDocumentResult(
            @JsonProperty(value = "id", required = true) String id,
            @JsonProperty(value = "warnings", required = true) List<DocumentWarning> warnings,
            @JsonProperty(value = "statistics", required = true) List<DocumentStatistics> statistics,
            @JsonProperty(value = "sentiment", required = true) DocumentSentimentValue sentiment,
            @JsonProperty(value = "sentences", required = true) List<SentenceSentiment> sentences,
            @JsonProperty(value = "confidenceScores", required = true)
                    SentimentConfidenceScorePerLabel confidenceScores) {
        this.id = id;
        this.warnings = warnings;
        this.statistics = statistics;
        this.sentiment = sentiment;
        this.sentences = sentences;
        this.confidenceScores = confidenceScores;
    }

    /**
     * Get the id property: Unique, non-empty document identifier.
     *
     * @return the id value.
     */
    public String getId() {
        return this.id;
    }

    /**
     * Get the warnings property: Warnings encountered while processing document.
     *
     * @return the warnings value.
     */
    public List<DocumentWarning> getWarnings() {
        return this.warnings;
    }

    /**
     * Get the statistics property: If showStats=true was specified in the request this field will contain information
     * about the document payload.
     *
     * @return the statistics value.
     */
    public List<DocumentStatistics> getStatistics() {
        return this.statistics;
    }

    /**
     * Get the sentiment property: Predicted sentiment for document.
     *
     * @return the sentiment value.
     */
    public DocumentSentimentValue getSentiment() {
        return this.sentiment;
    }

    /**
     * Get the sentences property: Sentence level sentiment analysis.
     *
     * @return the sentences value.
     */
    public List<SentenceSentiment> getSentences() {
        return this.sentences;
    }

    /**
     * Get the confidenceScores property: Document level sentiment confidence scores between 0 and 1 for each sentiment
     * class.
     *
     * @return the confidenceScores value.
     */
    public SentimentConfidenceScorePerLabel getConfidenceScores() {
        return this.confidenceScores;
    }
}
