// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.ai.language.textanalytics.models;

import com.azure.core.annotation.Immutable;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;

/** The SentimentConfidenceScorePerLabel model. */
@Immutable
public final class SentimentConfidenceScorePerLabel {
    /*
     * The positive property.
     */
    @JsonProperty(value = "positive", required = true)
    private double positive;

    /*
     * The negative property.
     */
    @JsonProperty(value = "negative", required = true)
    private double negative;

    /*
     * The neutral property.
     */
    @JsonProperty(value = "neutral", required = true)
    private double neutral;

    /**
     * Creates an instance of SentimentConfidenceScorePerLabel class.
     *
     * @param positive the positive value to set.
     * @param negative the negative value to set.
     * @param neutral the neutral value to set.
     */
    @JsonCreator
    public SentimentConfidenceScorePerLabel(
            @JsonProperty(value = "positive", required = true) double positive,
            @JsonProperty(value = "negative", required = true) double negative,
            @JsonProperty(value = "neutral", required = true) double neutral) {
        this.positive = positive;
        this.negative = negative;
        this.neutral = neutral;
    }

    /**
     * Get the positive property: The positive property.
     *
     * @return the positive value.
     */
    public double getPositive() {
        return this.positive;
    }

    /**
     * Get the negative property: The negative property.
     *
     * @return the negative value.
     */
    public double getNegative() {
        return this.negative;
    }

    /**
     * Get the neutral property: The neutral property.
     *
     * @return the neutral value.
     */
    public double getNeutral() {
        return this.neutral;
    }
}
