// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.ai.language.textanalytics.models;

import com.azure.core.util.ExpandableStringEnum;
import com.fasterxml.jackson.annotation.JsonCreator;
import java.util.Collection;

/** Defines values for WarningCode. */
public final class WarningCode extends ExpandableStringEnum<WarningCode> {
    /** Static value LongWordsInDocument for WarningCode. */
    public static final WarningCode LONG_WORDS_IN_DOCUMENT = fromString("LongWordsInDocument");

    /** Static value DocumentTruncated for WarningCode. */
    public static final WarningCode DOCUMENT_TRUNCATED = fromString("DocumentTruncated");

    /**
     * Creates or finds a WarningCode from its string representation.
     *
     * @param name a name to look for.
     * @return the corresponding WarningCode.
     */
    @JsonCreator
    public static WarningCode fromString(String name) {
        return fromString(name, WarningCode.class);
    }

    /**
     * Gets known WarningCode values.
     *
     * @return known WarningCode values.
     */
    public static Collection<WarningCode> values() {
        return values(WarningCode.class);
    }
}
