// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.ai.language.authoring;

import com.azure.core.util.ServiceVersion;

/** Service version of Authoring. */
public enum AuthoringServiceVersion implements ServiceVersion {
    /** Enum value 2022-05-15-preview. */
    V2022_05_15_PREVIEW("2022-05-15-preview");

    private final String version;

    AuthoringServiceVersion(String version) {
        this.version = version;
    }

    /** {@inheritDoc} */
    @Override
    public String getVersion() {
        return this.version;
    }

    /**
     * Gets the latest service version supported by this client library.
     *
     * @return The latest {@link AuthoringServiceVersion}.
     */
    public static AuthoringServiceVersion getLatest() {
        return V2022_05_15_PREVIEW;
    }
}
