// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.ai.language.authoring.implementation.models;

import com.azure.ai.language.authoring.models.Project;
import com.azure.core.annotation.Immutable;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;

/** Paged collection of Project items. */
@Immutable
public final class CustomPageProject {
    /*
     * The Project items on this page
     */
    @JsonProperty(value = "value", required = true)
    private List<Project> value;

    /*
     * The link to the next page of items
     */
    @JsonProperty(value = "nextLink")
    private String nextLink;

    /**
     * Creates an instance of CustomPageProject class.
     *
     * @param value the value value to set.
     */
    @JsonCreator
    private CustomPageProject(@JsonProperty(value = "value", required = true) List<Project> value) {
        this.value = value;
    }

    /**
     * Get the value property: The Project items on this page.
     *
     * @return the value value.
     */
    public List<Project> getValue() {
        return this.value;
    }

    /**
     * Get the nextLink property: The link to the next page of items.
     *
     * @return the nextLink value.
     */
    public String getNextLink() {
        return this.nextLink;
    }
}
