// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

/** Package containing the data models for MicrosoftCognitiveLanguageServiceAnalyzeTextAuthoring. */
package com.azure.ai.language.authoring.implementation.models;
