// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.ai.language.authoring.implementation;

import com.azure.ai.language.authoring.AuthoringServiceVersion;
import com.azure.core.http.HttpPipeline;
import com.azure.core.http.HttpPipelineBuilder;
import com.azure.core.http.policy.CookiePolicy;
import com.azure.core.http.policy.RetryPolicy;
import com.azure.core.http.policy.UserAgentPolicy;
import com.azure.core.util.serializer.JacksonAdapter;
import com.azure.core.util.serializer.SerializerAdapter;

/** Initializes a new instance of the AuthoringClient type. */
public final class AuthoringClientImpl {
    /** */
    private final String endpoint;

    /**
     * Gets.
     *
     * @return the endpoint value.
     */
    public String getEndpoint() {
        return this.endpoint;
    }

    /** Service version. */
    private final AuthoringServiceVersion serviceVersion;

    /**
     * Gets Service version.
     *
     * @return the serviceVersion value.
     */
    public AuthoringServiceVersion getServiceVersion() {
        return this.serviceVersion;
    }

    /** The HTTP pipeline to send requests through. */
    private final HttpPipeline httpPipeline;

    /**
     * Gets The HTTP pipeline to send requests through.
     *
     * @return the httpPipeline value.
     */
    public HttpPipeline getHttpPipeline() {
        return this.httpPipeline;
    }

    /** The serializer to serialize an object into a string. */
    private final SerializerAdapter serializerAdapter;

    /**
     * Gets The serializer to serialize an object into a string.
     *
     * @return the serializerAdapter value.
     */
    public SerializerAdapter getSerializerAdapter() {
        return this.serializerAdapter;
    }

    /** The ProjectsImpl object to access its operations. */
    private final ProjectsImpl projects;

    /**
     * Gets the ProjectsImpl object to access its operations.
     *
     * @return the ProjectsImpl object.
     */
    public ProjectsImpl getProjects() {
        return this.projects;
    }

    /** The DeploymentsImpl object to access its operations. */
    private final DeploymentsImpl deployments;

    /**
     * Gets the DeploymentsImpl object to access its operations.
     *
     * @return the DeploymentsImpl object.
     */
    public DeploymentsImpl getDeployments() {
        return this.deployments;
    }

    /** The JobsImpl object to access its operations. */
    private final JobsImpl jobs;

    /**
     * Gets the JobsImpl object to access its operations.
     *
     * @return the JobsImpl object.
     */
    public JobsImpl getJobs() {
        return this.jobs;
    }

    /** The GlobalsImpl object to access its operations. */
    private final GlobalsImpl globals;

    /**
     * Gets the GlobalsImpl object to access its operations.
     *
     * @return the GlobalsImpl object.
     */
    public GlobalsImpl getGlobals() {
        return this.globals;
    }

    /**
     * Initializes an instance of AuthoringClient client.
     *
     * @param endpoint
     * @param serviceVersion Service version.
     */
    public AuthoringClientImpl(String endpoint, AuthoringServiceVersion serviceVersion) {
        this(
                new HttpPipelineBuilder()
                        .policies(new UserAgentPolicy(), new RetryPolicy(), new CookiePolicy())
                        .build(),
                JacksonAdapter.createDefaultSerializerAdapter(),
                endpoint,
                serviceVersion);
    }

    /**
     * Initializes an instance of AuthoringClient client.
     *
     * @param httpPipeline The HTTP pipeline to send requests through.
     * @param endpoint
     * @param serviceVersion Service version.
     */
    public AuthoringClientImpl(HttpPipeline httpPipeline, String endpoint, AuthoringServiceVersion serviceVersion) {
        this(httpPipeline, JacksonAdapter.createDefaultSerializerAdapter(), endpoint, serviceVersion);
    }

    /**
     * Initializes an instance of AuthoringClient client.
     *
     * @param httpPipeline The HTTP pipeline to send requests through.
     * @param serializerAdapter The serializer to serialize an object into a string.
     * @param endpoint
     * @param serviceVersion Service version.
     */
    public AuthoringClientImpl(
            HttpPipeline httpPipeline,
            SerializerAdapter serializerAdapter,
            String endpoint,
            AuthoringServiceVersion serviceVersion) {
        this.httpPipeline = httpPipeline;
        this.serializerAdapter = serializerAdapter;
        this.endpoint = endpoint;
        this.serviceVersion = serviceVersion;
        this.projects = new ProjectsImpl(this);
        this.deployments = new DeploymentsImpl(this);
        this.jobs = new JobsImpl(this);
        this.globals = new GlobalsImpl(this);
    }
}
