// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.ai.language.authoring.models;

import com.azure.core.annotation.Fluent;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.Map;

/** The template for adding optional properties. */
@Fluent
public final class ProjectRequest {
    /*
     * The project kind.
     */
    @JsonProperty(value = "projectKind")
    private ProjectKind projectKind;

    /*
     * The storage container name.
     */
    @JsonProperty(value = "storageInputContainerName")
    private String storageInputContainerName;

    /*
     * The project settings.
     */
    @JsonProperty(value = "settings")
    private Map<String, String> settings;

    /*
     * Whether the project would be used for multiple languages or not.
     */
    @JsonProperty(value = "multilingual")
    private Boolean multilingual;

    /*
     * The project description.
     */
    @JsonProperty(value = "description")
    private String description;

    /*
     * The project language. This is BCP-47 representation of a language. For example, use "en" for English, "en-gb"
     * for English (UK), "es" for Spanish etc.
     */
    @JsonProperty(value = "language")
    private String language;

    /**
     * Get the projectKind property: The project kind.
     *
     * @return the projectKind value.
     */
    public ProjectKind getProjectKind() {
        return this.projectKind;
    }

    /**
     * Set the projectKind property: The project kind.
     *
     * @param projectKind the projectKind value to set.
     * @return the ProjectRequest object itself.
     */
    public ProjectRequest setProjectKind(ProjectKind projectKind) {
        this.projectKind = projectKind;
        return this;
    }

    /**
     * Get the storageInputContainerName property: The storage container name.
     *
     * @return the storageInputContainerName value.
     */
    public String getStorageInputContainerName() {
        return this.storageInputContainerName;
    }

    /**
     * Set the storageInputContainerName property: The storage container name.
     *
     * @param storageInputContainerName the storageInputContainerName value to set.
     * @return the ProjectRequest object itself.
     */
    public ProjectRequest setStorageInputContainerName(String storageInputContainerName) {
        this.storageInputContainerName = storageInputContainerName;
        return this;
    }

    /**
     * Get the settings property: The project settings.
     *
     * @return the settings value.
     */
    public Map<String, String> getSettings() {
        return this.settings;
    }

    /**
     * Set the settings property: The project settings.
     *
     * @param settings the settings value to set.
     * @return the ProjectRequest object itself.
     */
    public ProjectRequest setSettings(Map<String, String> settings) {
        this.settings = settings;
        return this;
    }

    /**
     * Get the multilingual property: Whether the project would be used for multiple languages or not.
     *
     * @return the multilingual value.
     */
    public Boolean isMultilingual() {
        return this.multilingual;
    }

    /**
     * Set the multilingual property: Whether the project would be used for multiple languages or not.
     *
     * @param multilingual the multilingual value to set.
     * @return the ProjectRequest object itself.
     */
    public ProjectRequest setMultilingual(Boolean multilingual) {
        this.multilingual = multilingual;
        return this;
    }

    /**
     * Get the description property: The project description.
     *
     * @return the description value.
     */
    public String getDescription() {
        return this.description;
    }

    /**
     * Set the description property: The project description.
     *
     * @param description the description value to set.
     * @return the ProjectRequest object itself.
     */
    public ProjectRequest setDescription(String description) {
        this.description = description;
        return this;
    }

    /**
     * Get the language property: The project language. This is BCP-47 representation of a language. For example, use
     * "en" for English, "en-gb" for English (UK), "es" for Spanish etc.
     *
     * @return the language value.
     */
    public String getLanguage() {
        return this.language;
    }

    /**
     * Set the language property: The project language. This is BCP-47 representation of a language. For example, use
     * "en" for English, "en-gb" for English (UK), "es" for Spanish etc.
     *
     * @param language the language value to set.
     * @return the ProjectRequest object itself.
     */
    public ProjectRequest setLanguage(String language) {
        this.language = language;
        return this;
    }
}
