// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.ai.language.authoring.models;

import com.azure.core.annotation.Immutable;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Swap deployment options
 *
 * <p>Define first name and second name for swap deployment options.
 */
@Immutable
public final class SwapDeploymentsOptions {
    /*
     * Deployment name
     *
     * Represents the first deployment name.
     */
    @JsonProperty(value = "firstDeploymentName", required = true)
    private String firstDeploymentName;

    /*
     * Deployment name
     *
     * Represents the second deployment name.
     */
    @JsonProperty(value = "secondDeploymentName", required = true)
    private String secondDeploymentName;

    /**
     * Creates an instance of SwapDeploymentsOptions class.
     *
     * @param firstDeploymentName the firstDeploymentName value to set.
     * @param secondDeploymentName the secondDeploymentName value to set.
     */
    @JsonCreator
    public SwapDeploymentsOptions(
            @JsonProperty(value = "firstDeploymentName", required = true) String firstDeploymentName,
            @JsonProperty(value = "secondDeploymentName", required = true) String secondDeploymentName) {
        this.firstDeploymentName = firstDeploymentName;
        this.secondDeploymentName = secondDeploymentName;
    }

    /**
     * Get the firstDeploymentName property: Deployment name
     *
     * <p>Represents the first deployment name.
     *
     * @return the firstDeploymentName value.
     */
    public String getFirstDeploymentName() {
        return this.firstDeploymentName;
    }

    /**
     * Get the secondDeploymentName property: Deployment name
     *
     * <p>Represents the second deployment name.
     *
     * @return the secondDeploymentName value.
     */
    public String getSecondDeploymentName() {
        return this.secondDeploymentName;
    }
}
