// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.ai.language.authoring.models;

import com.azure.core.annotation.Immutable;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;

/** Represents a training config version. */
@Immutable
public final class TrainingConfigVersion {
    /*
     * Represents the version of the config.
     */
    @JsonProperty(value = "trainingConfigVersion", required = true)
    private String trainingConfigVersion;

    /*
     * Represents the training config version expiration date.
     */
    @JsonProperty(value = "modelExpirationDate", required = true)
    private String modelExpirationDate;

    /**
     * Creates an instance of TrainingConfigVersion class.
     *
     * @param trainingConfigVersion the trainingConfigVersion value to set.
     * @param modelExpirationDate the modelExpirationDate value to set.
     */
    @JsonCreator
    private TrainingConfigVersion(
            @JsonProperty(value = "trainingConfigVersion", required = true) String trainingConfigVersion,
            @JsonProperty(value = "modelExpirationDate", required = true) String modelExpirationDate) {
        this.trainingConfigVersion = trainingConfigVersion;
        this.modelExpirationDate = modelExpirationDate;
    }

    /**
     * Get the trainingConfigVersion property: Represents the version of the config.
     *
     * @return the trainingConfigVersion value.
     */
    public String getTrainingConfigVersion() {
        return this.trainingConfigVersion;
    }

    /**
     * Get the modelExpirationDate property: Represents the training config version expiration date.
     *
     * @return the modelExpirationDate value.
     */
    public String getModelExpirationDate() {
        return this.modelExpirationDate;
    }
}
