// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.language.textanalytics.models;

import com.azure.core.annotation.Fluent;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;

/** The AnalyzeTextEntityRecognitionInput model. */
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "kind")
@JsonTypeName("AnalyzeTextEntityRecognitionInput")
@Fluent
public final class AnalyzeTextEntityRecognitionInput
        extends TaskEntityRecognitionEntitiesTaskParametersMultiLanguageAnalysisInput {
    /** {@inheritDoc} */
    @Override
    public AnalyzeTextEntityRecognitionInput setAnalysisInput(MultiLanguageAnalysisInput analysisInput) {
        super.setAnalysisInput(analysisInput);
        return this;
    }

    /** {@inheritDoc} */
    @Override
    public AnalyzeTextEntityRecognitionInput setParameters(EntitiesTaskParameters parameters) {
        super.setParameters(parameters);
        return this;
    }
}
