// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.language.textanalytics.models;

import com.azure.core.annotation.Immutable;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;

/** The AnalyzeTextTaskResult model. */
@JsonTypeInfo(
        use = JsonTypeInfo.Id.NAME,
        include = JsonTypeInfo.As.PROPERTY,
        property = "kind",
        defaultImpl = AnalyzeTextTaskResult.class)
@JsonTypeName("AnalyzeTextTaskResult")
@JsonSubTypes({
    @JsonSubTypes.Type(
            name = "EntityRecognitionResults",
            value = TaskResultEntityRecognitionResultsEntitiesResult.class),
    @JsonSubTypes.Type(name = "EntityLinkingResults", value = TaskResultEntityLinkingResultsEntityLinkingResult.class),
    @JsonSubTypes.Type(
            name = "KeyPhraseExtractionResults",
            value = TaskResultKeyPhraseExtractionResultsKeyPhraseResult.class),
    @JsonSubTypes.Type(
            name = "LanguageDetectionResults",
            value = TaskResultLanguageDetectionResultsLanguageDetectionResult.class),
    @JsonSubTypes.Type(
            name = "PiiEntityRecognitionResults",
            value = TaskResultPiiEntityRecognitionResultsPiiResult.class),
    @JsonSubTypes.Type(
            name = "SentimentAnalysisResults",
            value = TaskResultSentimentAnalysisResultsSentimentResponse.class)
})
@Immutable
public class AnalyzeTextTaskResult {}
