// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.language.textanalytics.models;

import com.azure.core.annotation.Fluent;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;

/** The AnalyzeTextKeyPhraseExtractionInput model. */
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "kind")
@JsonTypeName("AnalyzeTextKeyPhraseExtractionInput")
@Fluent
public final class AnalyzeTextKeyPhraseExtractionInput
        extends TaskKeyPhraseExtractionKeyPhraseTaskParametersMultiLanguageAnalysisInput {
    /** {@inheritDoc} */
    @Override
    public AnalyzeTextKeyPhraseExtractionInput setAnalysisInput(MultiLanguageAnalysisInput analysisInput) {
        super.setAnalysisInput(analysisInput);
        return this;
    }

    /** {@inheritDoc} */
    @Override
    public AnalyzeTextKeyPhraseExtractionInput setParameters(KeyPhraseTaskParameters parameters) {
        super.setParameters(parameters);
        return this;
    }
}
