// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.language.textanalytics.models;

import com.azure.core.annotation.Fluent;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;

/** The AnalyzeTextLanguageDetectionInput model. */
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "kind")
@JsonTypeName("AnalyzeTextLanguageDetectionInput")
@Fluent
public final class AnalyzeTextLanguageDetectionInput
        extends TaskLanguageDetectionLanguageDetectionTaskParametersLanguageDetectionAnalysisInput {
    /** {@inheritDoc} */
    @Override
    public AnalyzeTextLanguageDetectionInput setAnalysisInput(LanguageDetectionAnalysisInput analysisInput) {
        super.setAnalysisInput(analysisInput);
        return this;
    }

    /** {@inheritDoc} */
    @Override
    public AnalyzeTextLanguageDetectionInput setParameters(LanguageDetectionTaskParameters parameters) {
        super.setParameters(parameters);
        return this;
    }
}
