// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.language.textanalytics.models;

import com.azure.core.annotation.Fluent;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;

/** The DocumentWarning model. */
@Fluent
public final class DocumentWarning {
    /*
     * Warning code.
     */
    @JsonProperty(value = "code", required = true)
    private WarningCode code;

    /*
     * Warning message.
     */
    @JsonProperty(value = "message", required = true)
    private String message;

    /*
     * A JSON pointer reference indicating the target object.
     */
    @JsonProperty(value = "targetRef")
    private String targetRef;

    /**
     * Creates an instance of DocumentWarning class.
     *
     * @param code the code value to set.
     * @param message the message value to set.
     */
    @JsonCreator
    public DocumentWarning(
            @JsonProperty(value = "code", required = true) WarningCode code,
            @JsonProperty(value = "message", required = true) String message) {
        this.code = code;
        this.message = message;
    }

    /**
     * Get the code property: Warning code.
     *
     * @return the code value.
     */
    public WarningCode getCode() {
        return this.code;
    }

    /**
     * Get the message property: Warning message.
     *
     * @return the message value.
     */
    public String getMessage() {
        return this.message;
    }

    /**
     * Get the targetRef property: A JSON pointer reference indicating the target object.
     *
     * @return the targetRef value.
     */
    public String getTargetRef() {
        return this.targetRef;
    }

    /**
     * Set the targetRef property: A JSON pointer reference indicating the target object.
     *
     * @param targetRef the targetRef value to set.
     * @return the DocumentWarning object itself.
     */
    public DocumentWarning setTargetRef(String targetRef) {
        this.targetRef = targetRef;
        return this;
    }
}
