// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.language.textanalytics.models;

import com.azure.core.annotation.Fluent;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;

/** The EntityLinkingTaskResult model. */
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "kind")
@JsonTypeName("EntityLinkingResults")
@Fluent
public final class EntityLinkingTaskResult extends AnalyzeTextTaskResult {
    /*
     * The results property.
     */
    @JsonProperty(value = "results", required = true)
    private EntityLinkingResult results;

    /**
     * Creates an instance of EntityLinkingTaskResult class.
     *
     * @param results the results value to set.
     */
    @JsonCreator
    public EntityLinkingTaskResult(@JsonProperty(value = "results", required = true) EntityLinkingResult results) {
        this.results = results;
    }

    /**
     * Get the results property: The results property.
     *
     * @return the results value.
     */
    public EntityLinkingResult getResults() {
        return this.results;
    }
}
