// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.language.textanalytics.models;

import com.azure.core.annotation.Fluent;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;

/** The KeyPhrasesDocumentResult model. */
@Fluent
public final class KeyPhrasesDocumentResult {
    /*
     * Unique, non-empty document identifier.
     */
    @JsonProperty(value = "id", required = true)
    private String id;

    /*
     * Warnings encountered while processing document.
     */
    @JsonProperty(value = "warnings", required = true)
    private List<DocumentWarning> warnings;

    /*
     * If showStats=true was specified in the request this field will contain information about the document payload.
     */
    @JsonProperty(value = "statistics", required = true)
    private List<DocumentStatistics> statistics;

    /*
     * A list of representative words or phrases. The number of key phrases returned is proportional to the number of
     * words in the input document.
     */
    @JsonProperty(value = "keyPhrases", required = true)
    private List<String> keyPhrases;

    /**
     * Creates an instance of KeyPhrasesDocumentResult class.
     *
     * @param id the id value to set.
     * @param warnings the warnings value to set.
     * @param statistics the statistics value to set.
     * @param keyPhrases the keyPhrases value to set.
     */
    @JsonCreator
    public KeyPhrasesDocumentResult(
            @JsonProperty(value = "id", required = true) String id,
            @JsonProperty(value = "warnings", required = true) List<DocumentWarning> warnings,
            @JsonProperty(value = "statistics", required = true) List<DocumentStatistics> statistics,
            @JsonProperty(value = "keyPhrases", required = true) List<String> keyPhrases) {
        this.id = id;
        this.warnings = warnings;
        this.statistics = statistics;
        this.keyPhrases = keyPhrases;
    }

    /**
     * Get the id property: Unique, non-empty document identifier.
     *
     * @return the id value.
     */
    public String getId() {
        return this.id;
    }

    /**
     * Get the warnings property: Warnings encountered while processing document.
     *
     * @return the warnings value.
     */
    public List<DocumentWarning> getWarnings() {
        return this.warnings;
    }

    /**
     * Get the statistics property: If showStats=true was specified in the request this field will contain information
     * about the document payload.
     *
     * @return the statistics value.
     */
    public List<DocumentStatistics> getStatistics() {
        return this.statistics;
    }

    /**
     * Get the keyPhrases property: A list of representative words or phrases. The number of key phrases returned is
     * proportional to the number of words in the input document.
     *
     * @return the keyPhrases value.
     */
    public List<String> getKeyPhrases() {
        return this.keyPhrases;
    }
}
