// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.language.textanalytics.models;

import com.azure.core.annotation.Fluent;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;

/** The TargetRelation model. */
@Fluent
public final class TargetRelation {
    /*
     * The type related to the target.
     */
    @JsonProperty(value = "relationType", required = true)
    private TargetRelationType relationType;

    /*
     * The JSON pointer indicating the linked object.
     */
    @JsonProperty(value = "ref", required = true)
    private String ref;

    /**
     * Creates an instance of TargetRelation class.
     *
     * @param relationType the relationType value to set.
     * @param ref the ref value to set.
     */
    @JsonCreator
    public TargetRelation(
            @JsonProperty(value = "relationType", required = true) TargetRelationType relationType,
            @JsonProperty(value = "ref", required = true) String ref) {
        this.relationType = relationType;
        this.ref = ref;
    }

    /**
     * Get the relationType property: The type related to the target.
     *
     * @return the relationType value.
     */
    public TargetRelationType getRelationType() {
        return this.relationType;
    }

    /**
     * Get the ref property: The JSON pointer indicating the linked object.
     *
     * @return the ref value.
     */
    public String getRef() {
        return this.ref;
    }
}
