// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.language.textanalytics.models;

import com.azure.core.annotation.Fluent;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;

/** The TaskLanguageDetectionLanguageDetectionTaskParametersLanguageDetectionAnalysisInput model. */
@JsonTypeInfo(
        use = JsonTypeInfo.Id.NAME,
        include = JsonTypeInfo.As.PROPERTY,
        property = "kind",
        defaultImpl = TaskLanguageDetectionLanguageDetectionTaskParametersLanguageDetectionAnalysisInput.class)
@JsonTypeName("LanguageDetection")
@JsonSubTypes({
    @JsonSubTypes.Type(name = "AnalyzeTextLanguageDetectionInput", value = AnalyzeTextLanguageDetectionInput.class)
})
@Fluent
public class TaskLanguageDetectionLanguageDetectionTaskParametersLanguageDetectionAnalysisInput
        extends AnalyzeTextTask {
    /*
     * The analysisInput property.
     */
    @JsonProperty(value = "analysisInput")
    private LanguageDetectionAnalysisInput analysisInput;

    /*
     * The parameters property.
     */
    @JsonProperty(value = "parameters")
    private LanguageDetectionTaskParameters parameters;

    /**
     * Get the analysisInput property: The analysisInput property.
     *
     * @return the analysisInput value.
     */
    public LanguageDetectionAnalysisInput getAnalysisInput() {
        return this.analysisInput;
    }

    /**
     * Set the analysisInput property: The analysisInput property.
     *
     * @param analysisInput the analysisInput value to set.
     * @return the TaskLanguageDetectionLanguageDetectionTaskParametersLanguageDetectionAnalysisInput object itself.
     */
    public TaskLanguageDetectionLanguageDetectionTaskParametersLanguageDetectionAnalysisInput setAnalysisInput(
            LanguageDetectionAnalysisInput analysisInput) {
        this.analysisInput = analysisInput;
        return this;
    }

    /**
     * Get the parameters property: The parameters property.
     *
     * @return the parameters value.
     */
    public LanguageDetectionTaskParameters getParameters() {
        return this.parameters;
    }

    /**
     * Set the parameters property: The parameters property.
     *
     * @param parameters the parameters value to set.
     * @return the TaskLanguageDetectionLanguageDetectionTaskParametersLanguageDetectionAnalysisInput object itself.
     */
    public TaskLanguageDetectionLanguageDetectionTaskParametersLanguageDetectionAnalysisInput setParameters(
            LanguageDetectionTaskParameters parameters) {
        this.parameters = parameters;
        return this;
    }
}
