// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.language.textanalytics.models;

import com.azure.core.annotation.Fluent;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;

/** The PiiEntitiesDocumentResult model. */
@Fluent
public final class PiiEntitiesDocumentResult {
    /*
     * Unique, non-empty document identifier.
     */
    @JsonProperty(value = "id", required = true)
    private String id;

    /*
     * Warnings encountered while processing document.
     */
    @JsonProperty(value = "warnings", required = true)
    private List<DocumentWarning> warnings;

    /*
     * If showStats=true was specified in the request this field will contain information about the document payload.
     */
    @JsonProperty(value = "statistics", required = true)
    private List<DocumentStatistics> statistics;

    /*
     * Returns redacted text.
     */
    @JsonProperty(value = "redactedText")
    private String redactedText;

    /*
     * Recognized entities in the document.
     */
    @JsonProperty(value = "entities", required = true)
    private List<Entity> entities;

    /**
     * Creates an instance of PiiEntitiesDocumentResult class.
     *
     * @param id the id value to set.
     * @param warnings the warnings value to set.
     * @param statistics the statistics value to set.
     * @param entities the entities value to set.
     */
    @JsonCreator
    public PiiEntitiesDocumentResult(
            @JsonProperty(value = "id", required = true) String id,
            @JsonProperty(value = "warnings", required = true) List<DocumentWarning> warnings,
            @JsonProperty(value = "statistics", required = true) List<DocumentStatistics> statistics,
            @JsonProperty(value = "entities", required = true) List<Entity> entities) {
        this.id = id;
        this.warnings = warnings;
        this.statistics = statistics;
        this.entities = entities;
    }

    /**
     * Get the id property: Unique, non-empty document identifier.
     *
     * @return the id value.
     */
    public String getId() {
        return this.id;
    }

    /**
     * Get the warnings property: Warnings encountered while processing document.
     *
     * @return the warnings value.
     */
    public List<DocumentWarning> getWarnings() {
        return this.warnings;
    }

    /**
     * Get the statistics property: If showStats=true was specified in the request this field will contain information
     * about the document payload.
     *
     * @return the statistics value.
     */
    public List<DocumentStatistics> getStatistics() {
        return this.statistics;
    }

    /**
     * Get the redactedText property: Returns redacted text.
     *
     * @return the redactedText value.
     */
    public String getRedactedText() {
        return this.redactedText;
    }

    /**
     * Set the redactedText property: Returns redacted text.
     *
     * @param redactedText the redactedText value to set.
     * @return the PiiEntitiesDocumentResult object itself.
     */
    public PiiEntitiesDocumentResult setRedactedText(String redactedText) {
        this.redactedText = redactedText;
        return this;
    }

    /**
     * Get the entities property: Recognized entities in the document.
     *
     * @return the entities value.
     */
    public List<Entity> getEntities() {
        return this.entities;
    }
}
