// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.language.textanalytics.models;

import com.azure.core.annotation.Fluent;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;

/** The PiiTaskResult model. */
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "kind")
@JsonTypeName("PiiEntityRecognitionResults")
@Fluent
public final class PiiTaskResult extends AnalyzeTextTaskResult {
    /*
     * The results property.
     */
    @JsonProperty(value = "results", required = true)
    private PiiResult results;

    /**
     * Creates an instance of PiiTaskResult class.
     *
     * @param results the results value to set.
     */
    @JsonCreator
    public PiiTaskResult(@JsonProperty(value = "results", required = true) PiiResult results) {
        this.results = results;
    }

    /**
     * Get the results property: The results property.
     *
     * @return the results value.
     */
    public PiiResult getResults() {
        return this.results;
    }
}
