// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.language.textanalytics.models;

import com.azure.core.annotation.Fluent;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;

/** Supported parameters for a PII Entities Recognition task. */
@Fluent
public final class PiiTaskParameters {
    /*
     * If set to true, you opt-out of having your text input logged for troubleshooting.
     */
    @JsonProperty(value = "loggingOptOut")
    private Boolean loggingOptOut;

    /*
     * This field indicates which model is used for scoring.
     */
    @JsonProperty(value = "modelVersion")
    private String modelVersion;

    /*
     * Specifies the method used to interpret string offsets.
     *
     * Defaults to grapheme clusters according to Unicode v8.0.0.
     * For additional information see https://aka.ms/text-analytics-offsets
     */
    @JsonProperty(value = "stringIndexType")
    private StringIndexType stringIndexType;

    /*
     * If specified, will set the PII domain to include only a subset of the entity categories.
     */
    @JsonProperty(value = "domain")
    private PiiDomain domain;

    /*
     * Describes the PII categories to return.
     */
    @JsonProperty(value = "piiCategories")
    private List<PiiCategories> piiCategories;

    /**
     * Get the loggingOptOut property: If set to true, you opt-out of having your text input logged for troubleshooting.
     *
     * @return the loggingOptOut value.
     */
    public Boolean isLoggingOptOut() {
        return this.loggingOptOut;
    }

    /**
     * Set the loggingOptOut property: If set to true, you opt-out of having your text input logged for troubleshooting.
     *
     * @param loggingOptOut the loggingOptOut value to set.
     * @return the PiiTaskParameters object itself.
     */
    public PiiTaskParameters setLoggingOptOut(Boolean loggingOptOut) {
        this.loggingOptOut = loggingOptOut;
        return this;
    }

    /**
     * Get the modelVersion property: This field indicates which model is used for scoring.
     *
     * @return the modelVersion value.
     */
    public String getModelVersion() {
        return this.modelVersion;
    }

    /**
     * Set the modelVersion property: This field indicates which model is used for scoring.
     *
     * @param modelVersion the modelVersion value to set.
     * @return the PiiTaskParameters object itself.
     */
    public PiiTaskParameters setModelVersion(String modelVersion) {
        this.modelVersion = modelVersion;
        return this;
    }

    /**
     * Get the stringIndexType property: Specifies the method used to interpret string offsets.
     *
     * <p>Defaults to grapheme clusters according to Unicode v8.0.0. For additional information see
     * https://aka.ms/text-analytics-offsets.
     *
     * @return the stringIndexType value.
     */
    public StringIndexType getStringIndexType() {
        return this.stringIndexType;
    }

    /**
     * Set the stringIndexType property: Specifies the method used to interpret string offsets.
     *
     * <p>Defaults to grapheme clusters according to Unicode v8.0.0. For additional information see
     * https://aka.ms/text-analytics-offsets.
     *
     * @param stringIndexType the stringIndexType value to set.
     * @return the PiiTaskParameters object itself.
     */
    public PiiTaskParameters setStringIndexType(StringIndexType stringIndexType) {
        this.stringIndexType = stringIndexType;
        return this;
    }

    /**
     * Get the domain property: If specified, will set the PII domain to include only a subset of the entity categories.
     *
     * @return the domain value.
     */
    public PiiDomain getDomain() {
        return this.domain;
    }

    /**
     * Set the domain property: If specified, will set the PII domain to include only a subset of the entity categories.
     *
     * @param domain the domain value to set.
     * @return the PiiTaskParameters object itself.
     */
    public PiiTaskParameters setDomain(PiiDomain domain) {
        this.domain = domain;
        return this;
    }

    /**
     * Get the piiCategories property: Describes the PII categories to return.
     *
     * @return the piiCategories value.
     */
    public List<PiiCategories> getPiiCategories() {
        return this.piiCategories;
    }

    /**
     * Set the piiCategories property: Describes the PII categories to return.
     *
     * @param piiCategories the piiCategories value to set.
     * @return the PiiTaskParameters object itself.
     */
    public PiiTaskParameters setPiiCategories(List<PiiCategories> piiCategories) {
        this.piiCategories = piiCategories;
        return this;
    }
}
