// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.language.textanalytics.models;

import com.azure.core.annotation.Fluent;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;

/** The SentenceTarget model. */
@Fluent
public final class SentenceTarget {
    /*
     * Targeted sentiment in the sentence.
     */
    @JsonProperty(value = "sentiment", required = true)
    private TokenSentimentValue sentiment;

    /*
     * Target sentiment confidence scores for the target in the sentence.
     */
    @JsonProperty(value = "confidenceScores", required = true)
    private TargetConfidenceScoreLabel confidenceScores;

    /*
     * The target offset from the start of the sentence.
     */
    @JsonProperty(value = "offset", required = true)
    private long offset;

    /*
     * The length of the target.
     */
    @JsonProperty(value = "length", required = true)
    private long length;

    /*
     * The target text detected.
     */
    @JsonProperty(value = "text", required = true)
    private String text;

    /*
     * The array of either assessment or target objects which is related to the target.
     */
    @JsonProperty(value = "relations", required = true)
    private List<TargetRelation> relations;

    /**
     * Creates an instance of SentenceTarget class.
     *
     * @param sentiment the sentiment value to set.
     * @param confidenceScores the confidenceScores value to set.
     * @param offset the offset value to set.
     * @param length the length value to set.
     * @param text the text value to set.
     * @param relations the relations value to set.
     */
    @JsonCreator
    public SentenceTarget(
            @JsonProperty(value = "sentiment", required = true) TokenSentimentValue sentiment,
            @JsonProperty(value = "confidenceScores", required = true) TargetConfidenceScoreLabel confidenceScores,
            @JsonProperty(value = "offset", required = true) long offset,
            @JsonProperty(value = "length", required = true) long length,
            @JsonProperty(value = "text", required = true) String text,
            @JsonProperty(value = "relations", required = true) List<TargetRelation> relations) {
        this.sentiment = sentiment;
        this.confidenceScores = confidenceScores;
        this.offset = offset;
        this.length = length;
        this.text = text;
        this.relations = relations;
    }

    /**
     * Get the sentiment property: Targeted sentiment in the sentence.
     *
     * @return the sentiment value.
     */
    public TokenSentimentValue getSentiment() {
        return this.sentiment;
    }

    /**
     * Get the confidenceScores property: Target sentiment confidence scores for the target in the sentence.
     *
     * @return the confidenceScores value.
     */
    public TargetConfidenceScoreLabel getConfidenceScores() {
        return this.confidenceScores;
    }

    /**
     * Get the offset property: The target offset from the start of the sentence.
     *
     * @return the offset value.
     */
    public long getOffset() {
        return this.offset;
    }

    /**
     * Get the length property: The length of the target.
     *
     * @return the length value.
     */
    public long getLength() {
        return this.length;
    }

    /**
     * Get the text property: The target text detected.
     *
     * @return the text value.
     */
    public String getText() {
        return this.text;
    }

    /**
     * Get the relations property: The array of either assessment or target objects which is related to the target.
     *
     * @return the relations value.
     */
    public List<TargetRelation> getRelations() {
        return this.relations;
    }
}
